# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2.1.1
        with:
          path: node_modules
          key: ${{runner.OS}}-build-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.OS }}-build-${{ runner.OS }}-
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          PERSONAL_TOKEN: ${{secrets.GH_DEPLOY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
